# Generated by Django 4.2.3 on 2023-07-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
                ('rollno', models.CharField(max_length=13)),
                ('course', models.CharField(max_length=15)),
                ('clas', models.CharField(max_length=7)),
                ('img', models.FileField(upload_to='images')),
            ],
        ),
    ]
